version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_club
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: vpc
      MYSQL_USER: vpcuser
      MYSQL_PASSWORD: vpcpassword
    ports:
       - '3307:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  spring-api:
    build: ./vpc-api
    ports:
      - '8080:8080'
    depends_on:
      - mysql
